//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能导致不正确的行为，并在以下条件下丢失:
//     代码重新生成。
// </auto-generated>
//------------------------------------------------------------------------------

namespace weaver
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="webservices.services.weaver.com.cn", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowRequestInfo", Namespace="http://webservices.workflow.weaver")]
    public partial class WorkflowRequestInfo : object
    {
        
        private bool canEditField;
        
        private bool canViewField;
        
        private string createTimeField;
        
        private string creatorIdField;
        
        private string creatorNameField;
        
        private string currentNodeIdField;
        
        private string currentNodeNameField;
        
        private string forwardButtonNameField;
        
        private string isnextflowField;
        
        private string lastOperateTimeField;
        
        private string lastOperatorNameField;
        
        private string messageTypeField;
        
        private bool mustInputRemarkField;
        
        private bool needAffirmanceField;
        
        private string receiveTimeField;
        
        private string rejectButtonNameField;
        
        private string remarkField;
        
        private string requestIdField;
        
        private string requestLevelField;
        
        private string requestNameField;
        
        private string statusField;
        
        private string subbackButtonNameField;
        
        private string submitButtonNameField;
        
        private string subnobackButtonNameField;
        
        private weaver.WorkflowBaseInfo workflowBaseInfoField;
        
        private weaver.WorkflowDetailTableInfo[] workflowDetailTableInfosField;
        
        private weaver.ArrayOfString workflowHtmlShowField;
        
        private weaver.ArrayOfString workflowHtmlTempleteField;
        
        private weaver.WorkflowMainTableInfo workflowMainTableInfoField;
        
        private weaver.ArrayOfString[] workflowPhrasesField;
        
        private weaver.WorkflowRequestLog[] workflowRequestLogsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool canEdit
        {
            get
            {
                return this.canEditField;
            }
            set
            {
                this.canEditField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool canView
        {
            get
            {
                return this.canViewField;
            }
            set
            {
                this.canViewField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string createTime
        {
            get
            {
                return this.createTimeField;
            }
            set
            {
                this.createTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string creatorId
        {
            get
            {
                return this.creatorIdField;
            }
            set
            {
                this.creatorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string creatorName
        {
            get
            {
                return this.creatorNameField;
            }
            set
            {
                this.creatorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currentNodeId
        {
            get
            {
                return this.currentNodeIdField;
            }
            set
            {
                this.currentNodeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currentNodeName
        {
            get
            {
                return this.currentNodeNameField;
            }
            set
            {
                this.currentNodeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string forwardButtonName
        {
            get
            {
                return this.forwardButtonNameField;
            }
            set
            {
                this.forwardButtonNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isnextflow
        {
            get
            {
                return this.isnextflowField;
            }
            set
            {
                this.isnextflowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastOperateTime
        {
            get
            {
                return this.lastOperateTimeField;
            }
            set
            {
                this.lastOperateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastOperatorName
        {
            get
            {
                return this.lastOperatorNameField;
            }
            set
            {
                this.lastOperatorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string messageType
        {
            get
            {
                return this.messageTypeField;
            }
            set
            {
                this.messageTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool mustInputRemark
        {
            get
            {
                return this.mustInputRemarkField;
            }
            set
            {
                this.mustInputRemarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool needAffirmance
        {
            get
            {
                return this.needAffirmanceField;
            }
            set
            {
                this.needAffirmanceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string receiveTime
        {
            get
            {
                return this.receiveTimeField;
            }
            set
            {
                this.receiveTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rejectButtonName
        {
            get
            {
                return this.rejectButtonNameField;
            }
            set
            {
                this.rejectButtonNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string requestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string requestLevel
        {
            get
            {
                return this.requestLevelField;
            }
            set
            {
                this.requestLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string requestName
        {
            get
            {
                return this.requestNameField;
            }
            set
            {
                this.requestNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subbackButtonName
        {
            get
            {
                return this.subbackButtonNameField;
            }
            set
            {
                this.subbackButtonNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string submitButtonName
        {
            get
            {
                return this.submitButtonNameField;
            }
            set
            {
                this.submitButtonNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string subnobackButtonName
        {
            get
            {
                return this.subnobackButtonNameField;
            }
            set
            {
                this.subnobackButtonNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public weaver.WorkflowBaseInfo workflowBaseInfo
        {
            get
            {
                return this.workflowBaseInfoField;
            }
            set
            {
                this.workflowBaseInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public weaver.WorkflowDetailTableInfo[] workflowDetailTableInfos
        {
            get
            {
                return this.workflowDetailTableInfosField;
            }
            set
            {
                this.workflowDetailTableInfosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public weaver.ArrayOfString workflowHtmlShow
        {
            get
            {
                return this.workflowHtmlShowField;
            }
            set
            {
                this.workflowHtmlShowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public weaver.ArrayOfString workflowHtmlTemplete
        {
            get
            {
                return this.workflowHtmlTempleteField;
            }
            set
            {
                this.workflowHtmlTempleteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public weaver.WorkflowMainTableInfo workflowMainTableInfo
        {
            get
            {
                return this.workflowMainTableInfoField;
            }
            set
            {
                this.workflowMainTableInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public weaver.ArrayOfString[] workflowPhrases
        {
            get
            {
                return this.workflowPhrasesField;
            }
            set
            {
                this.workflowPhrasesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public weaver.WorkflowRequestLog[] workflowRequestLogs
        {
            get
            {
                return this.workflowRequestLogsField;
            }
            set
            {
                this.workflowRequestLogsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowBaseInfo", Namespace="http://webservices.workflow.weaver")]
    public partial class WorkflowBaseInfo : object
    {
        
        private string workflowIdField;
        
        private string workflowNameField;
        
        private string workflowTypeIdField;
        
        private string workflowTypeNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string workflowId
        {
            get
            {
                return this.workflowIdField;
            }
            set
            {
                this.workflowIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string workflowName
        {
            get
            {
                return this.workflowNameField;
            }
            set
            {
                this.workflowNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string workflowTypeId
        {
            get
            {
                return this.workflowTypeIdField;
            }
            set
            {
                this.workflowTypeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string workflowTypeName
        {
            get
            {
                return this.workflowTypeNameField;
            }
            set
            {
                this.workflowTypeNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowMainTableInfo", Namespace="http://webservices.workflow.weaver")]
    public partial class WorkflowMainTableInfo : object
    {
        
        private weaver.WorkflowRequestTableRecord[] requestRecordsField;
        
        private string tableDBNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public weaver.WorkflowRequestTableRecord[] requestRecords
        {
            get
            {
                return this.requestRecordsField;
            }
            set
            {
                this.requestRecordsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tableDBName
        {
            get
            {
                return this.tableDBNameField;
            }
            set
            {
                this.tableDBNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowDetailTableInfo", Namespace="http://webservices.workflow.weaver")]
    public partial class WorkflowDetailTableInfo : object
    {
        
        private string tableDBNameField;
        
        private weaver.ArrayOfString tableFieldNameField;
        
        private string tableTitleField;
        
        private weaver.WorkflowRequestTableRecord[] workflowRequestTableRecordsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tableDBName
        {
            get
            {
                return this.tableDBNameField;
            }
            set
            {
                this.tableDBNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public weaver.ArrayOfString tableFieldName
        {
            get
            {
                return this.tableFieldNameField;
            }
            set
            {
                this.tableFieldNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tableTitle
        {
            get
            {
                return this.tableTitleField;
            }
            set
            {
                this.tableTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public weaver.WorkflowRequestTableRecord[] workflowRequestTableRecords
        {
            get
            {
                return this.workflowRequestTableRecordsField;
            }
            set
            {
                this.workflowRequestTableRecordsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowRequestLog", Namespace="http://webservices.workflow.weaver")]
    public partial class WorkflowRequestLog : object
    {
        
        private string agentorField;
        
        private string agentorDeptField;
        
        private string annexDocHtmlsField;
        
        private string idField;
        
        private string nodeIdField;
        
        private string nodeNameField;
        
        private string operateDateField;
        
        private string operateTimeField;
        
        private string operateTypeField;
        
        private string operatorDeptField;
        
        private string operatorIdField;
        
        private string operatorNameField;
        
        private string operatorSignField;
        
        private string receivedPersonsField;
        
        private string remarkField;
        
        private string remarkSignField;
        
        private string signDocHtmlsField;
        
        private string signWorkFlowHtmlsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string agentor
        {
            get
            {
                return this.agentorField;
            }
            set
            {
                this.agentorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string agentorDept
        {
            get
            {
                return this.agentorDeptField;
            }
            set
            {
                this.agentorDeptField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string annexDocHtmls
        {
            get
            {
                return this.annexDocHtmlsField;
            }
            set
            {
                this.annexDocHtmlsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nodeId
        {
            get
            {
                return this.nodeIdField;
            }
            set
            {
                this.nodeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nodeName
        {
            get
            {
                return this.nodeNameField;
            }
            set
            {
                this.nodeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operateDate
        {
            get
            {
                return this.operateDateField;
            }
            set
            {
                this.operateDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operateTime
        {
            get
            {
                return this.operateTimeField;
            }
            set
            {
                this.operateTimeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operateType
        {
            get
            {
                return this.operateTypeField;
            }
            set
            {
                this.operateTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operatorDept
        {
            get
            {
                return this.operatorDeptField;
            }
            set
            {
                this.operatorDeptField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operatorId
        {
            get
            {
                return this.operatorIdField;
            }
            set
            {
                this.operatorIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operatorName
        {
            get
            {
                return this.operatorNameField;
            }
            set
            {
                this.operatorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string operatorSign
        {
            get
            {
                return this.operatorSignField;
            }
            set
            {
                this.operatorSignField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string receivedPersons
        {
            get
            {
                return this.receivedPersonsField;
            }
            set
            {
                this.receivedPersonsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remark
        {
            get
            {
                return this.remarkField;
            }
            set
            {
                this.remarkField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string remarkSign
        {
            get
            {
                return this.remarkSignField;
            }
            set
            {
                this.remarkSignField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string signDocHtmls
        {
            get
            {
                return this.signDocHtmlsField;
            }
            set
            {
                this.signDocHtmlsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string signWorkFlowHtmls
        {
            get
            {
                return this.signWorkFlowHtmlsField;
            }
            set
            {
                this.signWorkFlowHtmlsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowRequestTableRecord", Namespace="http://webservices.workflow.weaver")]
    public partial class WorkflowRequestTableRecord : object
    {
        
        private int recordOrderField;
        
        private weaver.WorkflowRequestTableField[] workflowRequestTableFieldsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int recordOrder
        {
            get
            {
                return this.recordOrderField;
            }
            set
            {
                this.recordOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public weaver.WorkflowRequestTableField[] workflowRequestTableFields
        {
            get
            {
                return this.workflowRequestTableFieldsField;
            }
            set
            {
                this.workflowRequestTableFieldsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkflowRequestTableField", Namespace="http://webservices.workflow.weaver")]
    public partial class WorkflowRequestTableField : object
    {
        
        private string browserurlField;
        
        private bool editField;
        
        private string fieldDBTypeField;
        
        private string fieldFormNameField;
        
        private string fieldHtmlTypeField;
        
        private string fieldIdField;
        
        private string fieldNameField;
        
        private int fieldOrderField;
        
        private string fieldShowNameField;
        
        private string fieldShowValueField;
        
        private string fieldTypeField;
        
        private string fieldValueField;
        
        private string filedHtmlShowField;
        
        private bool mandField;
        
        private weaver.ArrayOfString selectnamesField;
        
        private weaver.ArrayOfString selectvaluesField;
        
        private bool viewField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string browserurl
        {
            get
            {
                return this.browserurlField;
            }
            set
            {
                this.browserurlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool edit
        {
            get
            {
                return this.editField;
            }
            set
            {
                this.editField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fieldDBType
        {
            get
            {
                return this.fieldDBTypeField;
            }
            set
            {
                this.fieldDBTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fieldFormName
        {
            get
            {
                return this.fieldFormNameField;
            }
            set
            {
                this.fieldFormNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fieldHtmlType
        {
            get
            {
                return this.fieldHtmlTypeField;
            }
            set
            {
                this.fieldHtmlTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fieldId
        {
            get
            {
                return this.fieldIdField;
            }
            set
            {
                this.fieldIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fieldName
        {
            get
            {
                return this.fieldNameField;
            }
            set
            {
                this.fieldNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int fieldOrder
        {
            get
            {
                return this.fieldOrderField;
            }
            set
            {
                this.fieldOrderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fieldShowName
        {
            get
            {
                return this.fieldShowNameField;
            }
            set
            {
                this.fieldShowNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fieldShowValue
        {
            get
            {
                return this.fieldShowValueField;
            }
            set
            {
                this.fieldShowValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fieldType
        {
            get
            {
                return this.fieldTypeField;
            }
            set
            {
                this.fieldTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fieldValue
        {
            get
            {
                return this.fieldValueField;
            }
            set
            {
                this.fieldValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string filedHtmlShow
        {
            get
            {
                return this.filedHtmlShowField;
            }
            set
            {
                this.filedHtmlShowField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool mand
        {
            get
            {
                return this.mandField;
            }
            set
            {
                this.mandField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public weaver.ArrayOfString selectnames
        {
            get
            {
                return this.selectnamesField;
            }
            set
            {
                this.selectnamesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public weaver.ArrayOfString selectvalues
        {
            get
            {
                return this.selectvaluesField;
            }
            set
            {
                this.selectvaluesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool view
        {
            get
            {
                return this.viewField;
            }
            set
            {
                this.viewField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="webservices.services.weaver.com.cn", ConfigurationName="weaver.WorkflowServicePortType")]
    public interface WorkflowServicePortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.forward2WorkflowRequest", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> forward2WorkflowRequestAsync(int in0, string in1, string in2, int in3, string in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getAllWorkflowRequestList", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<weaver.WorkflowRequestInfo[]> getAllWorkflowRequestListAsync(int in0, int in1, int in2, int in3, weaver.ArrayOfString in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getWorkflowRequest", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<weaver.WorkflowRequestInfo> getWorkflowRequestAsync(int in0, int in1, int in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getHendledWorkflowRequestList", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<weaver.WorkflowRequestInfo[]> getHendledWorkflowRequestListAsync(int in0, int in1, int in2, int in3, weaver.ArrayOfString in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getToDoWorkflowRequestList", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<weaver.WorkflowRequestInfo[]> getToDoWorkflowRequestListAsync(int in0, int in1, int in2, int in3, weaver.ArrayOfString in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getWorkflowRequest4split", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<weaver.WorkflowRequestInfo> getWorkflowRequest4splitAsync(int in0, int in1, int in2, int in3);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.submitWorkflowRequest", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> submitWorkflowRequestAsync(weaver.WorkflowRequestInfo in0, int in1, int in2, string in3, string in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getHendledWorkflowRequestCount", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<int> getHendledWorkflowRequestCountAsync(int in0, weaver.ArrayOfString in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getLeaveDays", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getLeaveDaysAsync(string in0, string in1, string in2, string in3, string in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowList", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<weaver.WorkflowBaseInfo[]> getCreateWorkflowListAsync(int in0, int in1, int in2, int in3, int in4, weaver.ArrayOfString in5);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowCount", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<int> getCreateWorkflowCountAsync(int in0, int in1, weaver.ArrayOfString in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getProcessedWorkflowRequestCount", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<int> getProcessedWorkflowRequestCountAsync(int in0, weaver.ArrayOfString in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.forwardWorkflowRequest", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> forwardWorkflowRequestAsync(int in0, string in1, string in2, int in3, string in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.doCreateWorkflowRequest", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> doCreateWorkflowRequestAsync(weaver.WorkflowRequestInfo in0, int in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.doForceOver", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> doForceOverAsync(int in0, int in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getCCWorkflowRequestCount", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<int> getCCWorkflowRequestCountAsync(int in0, weaver.ArrayOfString in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getProcessedWorkflowRequestList", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<weaver.WorkflowRequestInfo[]> getProcessedWorkflowRequestListAsync(int in0, int in1, int in2, int in3, weaver.ArrayOfString in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getAllWorkflowRequestCount", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<int> getAllWorkflowRequestCountAsync(int in0, weaver.ArrayOfString in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowRequestInfo", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<weaver.WorkflowRequestInfo> getCreateWorkflowRequestInfoAsync(int in0, int in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getMyWorkflowRequestList", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<weaver.WorkflowRequestInfo[]> getMyWorkflowRequestListAsync(int in0, int in1, int in2, int in3, weaver.ArrayOfString in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowTypeList", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<weaver.WorkflowBaseInfo[]> getCreateWorkflowTypeListAsync(int in0, int in1, int in2, int in3, weaver.ArrayOfString in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getMyWorkflowRequestCount", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<int> getMyWorkflowRequestCountAsync(int in0, weaver.ArrayOfString in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getWorkflowNewFlag", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<weaver.ArrayOfString> getWorkflowNewFlagAsync(weaver.ArrayOfString in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.writeWorkflowReadFlag", ReplyAction="*")]
        System.Threading.Tasks.Task writeWorkflowReadFlagAsync(string in0, string in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getToDoWorkflowRequestCount", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<int> getToDoWorkflowRequestCountAsync(int in0, weaver.ArrayOfString in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.givingOpinions", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> givingOpinionsAsync(int in0, int in1, string in2);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getCreateWorkflowTypeCount", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<int> getCreateWorkflowTypeCountAsync(int in0, weaver.ArrayOfString in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getWorkflowRequestLogs", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<weaver.WorkflowRequestLog[]> getWorkflowRequestLogsAsync(string in0, string in1, int in2, int in3, int in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.deleteRequest", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<bool> deleteRequestAsync(int in0, int in1);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getCCWorkflowRequestList", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<weaver.WorkflowRequestInfo[]> getCCWorkflowRequestListAsync(int in0, int in1, int in2, int in3, weaver.ArrayOfString in4);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:weaver.workflow.webservices.WorkflowService.getUserid", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="out")]
        System.Threading.Tasks.Task<string> getUserIdAsync(string in0, string in1);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface WorkflowServicePortTypeChannel : weaver.WorkflowServicePortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class WorkflowServicePortTypeClient : System.ServiceModel.ClientBase<weaver.WorkflowServicePortType>, weaver.WorkflowServicePortType
    {
        
        /// <summary>
        /// 实现此分部方法，配置服务终结点。
        /// </summary>
        /// <param name="serviceEndpoint">要配置的终结点</param>
        /// <param name="clientCredentials">客户端凭据</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WorkflowServicePortTypeClient() : 
                base(WorkflowServicePortTypeClient.GetDefaultBinding(), WorkflowServicePortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.WorkflowServiceHttpPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WorkflowServicePortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(WorkflowServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), WorkflowServicePortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WorkflowServicePortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WorkflowServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WorkflowServicePortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WorkflowServicePortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WorkflowServicePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> forward2WorkflowRequestAsync(int in0, string in1, string in2, int in3, string in4)
        {
            return base.Channel.forward2WorkflowRequestAsync(in0, in1, in2, in3, in4);
        }
        
        public System.Threading.Tasks.Task<weaver.WorkflowRequestInfo[]> getAllWorkflowRequestListAsync(int in0, int in1, int in2, int in3, weaver.ArrayOfString in4)
        {
            return base.Channel.getAllWorkflowRequestListAsync(in0, in1, in2, in3, in4);
        }
        
        public System.Threading.Tasks.Task<weaver.WorkflowRequestInfo> getWorkflowRequestAsync(int in0, int in1, int in2)
        {
            return base.Channel.getWorkflowRequestAsync(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<weaver.WorkflowRequestInfo[]> getHendledWorkflowRequestListAsync(int in0, int in1, int in2, int in3, weaver.ArrayOfString in4)
        {
            return base.Channel.getHendledWorkflowRequestListAsync(in0, in1, in2, in3, in4);
        }
        
        public System.Threading.Tasks.Task<weaver.WorkflowRequestInfo[]> getToDoWorkflowRequestListAsync(int in0, int in1, int in2, int in3, weaver.ArrayOfString in4)
        {
            return base.Channel.getToDoWorkflowRequestListAsync(in0, in1, in2, in3, in4);
        }
        
        public System.Threading.Tasks.Task<weaver.WorkflowRequestInfo> getWorkflowRequest4splitAsync(int in0, int in1, int in2, int in3)
        {
            return base.Channel.getWorkflowRequest4splitAsync(in0, in1, in2, in3);
        }
        
        public System.Threading.Tasks.Task<string> submitWorkflowRequestAsync(weaver.WorkflowRequestInfo in0, int in1, int in2, string in3, string in4)
        {
            return base.Channel.submitWorkflowRequestAsync(in0, in1, in2, in3, in4);
        }
        
        public System.Threading.Tasks.Task<int> getHendledWorkflowRequestCountAsync(int in0, weaver.ArrayOfString in1)
        {
            return base.Channel.getHendledWorkflowRequestCountAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> getLeaveDaysAsync(string in0, string in1, string in2, string in3, string in4)
        {
            return base.Channel.getLeaveDaysAsync(in0, in1, in2, in3, in4);
        }
        
        public System.Threading.Tasks.Task<weaver.WorkflowBaseInfo[]> getCreateWorkflowListAsync(int in0, int in1, int in2, int in3, int in4, weaver.ArrayOfString in5)
        {
            return base.Channel.getCreateWorkflowListAsync(in0, in1, in2, in3, in4, in5);
        }
        
        public System.Threading.Tasks.Task<int> getCreateWorkflowCountAsync(int in0, int in1, weaver.ArrayOfString in2)
        {
            return base.Channel.getCreateWorkflowCountAsync(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<int> getProcessedWorkflowRequestCountAsync(int in0, weaver.ArrayOfString in1)
        {
            return base.Channel.getProcessedWorkflowRequestCountAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> forwardWorkflowRequestAsync(int in0, string in1, string in2, int in3, string in4)
        {
            return base.Channel.forwardWorkflowRequestAsync(in0, in1, in2, in3, in4);
        }
        
        public System.Threading.Tasks.Task<string> doCreateWorkflowRequestAsync(weaver.WorkflowRequestInfo in0, int in1)
        {
            return base.Channel.doCreateWorkflowRequestAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> doForceOverAsync(int in0, int in1)
        {
            return base.Channel.doForceOverAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<int> getCCWorkflowRequestCountAsync(int in0, weaver.ArrayOfString in1)
        {
            return base.Channel.getCCWorkflowRequestCountAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<weaver.WorkflowRequestInfo[]> getProcessedWorkflowRequestListAsync(int in0, int in1, int in2, int in3, weaver.ArrayOfString in4)
        {
            return base.Channel.getProcessedWorkflowRequestListAsync(in0, in1, in2, in3, in4);
        }
        
        public System.Threading.Tasks.Task<int> getAllWorkflowRequestCountAsync(int in0, weaver.ArrayOfString in1)
        {
            return base.Channel.getAllWorkflowRequestCountAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<weaver.WorkflowRequestInfo> getCreateWorkflowRequestInfoAsync(int in0, int in1)
        {
            return base.Channel.getCreateWorkflowRequestInfoAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<weaver.WorkflowRequestInfo[]> getMyWorkflowRequestListAsync(int in0, int in1, int in2, int in3, weaver.ArrayOfString in4)
        {
            return base.Channel.getMyWorkflowRequestListAsync(in0, in1, in2, in3, in4);
        }
        
        public System.Threading.Tasks.Task<weaver.WorkflowBaseInfo[]> getCreateWorkflowTypeListAsync(int in0, int in1, int in2, int in3, weaver.ArrayOfString in4)
        {
            return base.Channel.getCreateWorkflowTypeListAsync(in0, in1, in2, in3, in4);
        }
        
        public System.Threading.Tasks.Task<int> getMyWorkflowRequestCountAsync(int in0, weaver.ArrayOfString in1)
        {
            return base.Channel.getMyWorkflowRequestCountAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<weaver.ArrayOfString> getWorkflowNewFlagAsync(weaver.ArrayOfString in0, string in1)
        {
            return base.Channel.getWorkflowNewFlagAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task writeWorkflowReadFlagAsync(string in0, string in1)
        {
            return base.Channel.writeWorkflowReadFlagAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<int> getToDoWorkflowRequestCountAsync(int in0, weaver.ArrayOfString in1)
        {
            return base.Channel.getToDoWorkflowRequestCountAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<string> givingOpinionsAsync(int in0, int in1, string in2)
        {
            return base.Channel.givingOpinionsAsync(in0, in1, in2);
        }
        
        public System.Threading.Tasks.Task<int> getCreateWorkflowTypeCountAsync(int in0, weaver.ArrayOfString in1)
        {
            return base.Channel.getCreateWorkflowTypeCountAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<weaver.WorkflowRequestLog[]> getWorkflowRequestLogsAsync(string in0, string in1, int in2, int in3, int in4)
        {
            return base.Channel.getWorkflowRequestLogsAsync(in0, in1, in2, in3, in4);
        }
        
        public System.Threading.Tasks.Task<bool> deleteRequestAsync(int in0, int in1)
        {
            return base.Channel.deleteRequestAsync(in0, in1);
        }
        
        public System.Threading.Tasks.Task<weaver.WorkflowRequestInfo[]> getCCWorkflowRequestListAsync(int in0, int in1, int in2, int in3, weaver.ArrayOfString in4)
        {
            return base.Channel.getCCWorkflowRequestListAsync(in0, in1, in2, in3, in4);
        }
        
        public System.Threading.Tasks.Task<string> getUserIdAsync(string in0, string in1)
        {
            return base.Channel.getUserIdAsync(in0, in1);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WorkflowServiceHttpPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WorkflowServiceHttpPort))
            {
                return new System.ServiceModel.EndpointAddress("http://10.0.10.210/services/WorkflowService");
            }
            throw new System.InvalidOperationException(string.Format("找不到名称为“{0}”的终结点。", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return WorkflowServicePortTypeClient.GetBindingForEndpoint(EndpointConfiguration.WorkflowServiceHttpPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return WorkflowServicePortTypeClient.GetEndpointAddress(EndpointConfiguration.WorkflowServiceHttpPort);
        }
        
        public enum EndpointConfiguration
        {
            
            WorkflowServiceHttpPort,
        }
    }
}
